_target_: fusion_bench.method.yongxianwei_merging.algorithm.YongxianweiMergingAlgorithm
_recursive_: false
method_name: wudi
scaling_coefficient: 1.0
exclude_param_names_regex: []
merge_device: null
load_on_cpu: false
strict: false
method_kwargs:
  iter_num: 300
  learning_rate: 0.00001
